### ISSUE TITLE
Doesn't work in OSX

### ISSUE THREAD

**Issue by mattkanwisher** [rcrowley/goagain#4] opened 2013-02-23 04:54 UTC
I'm really confused why this doesn't work in OSX, the sub process always says that "dup: bad file descriptor" . But I have it working fine on linux. Any ideas of what to look at?

**Comment by mattkanwisher** [comment] 2013-02-23 05:11
Tracked it down a bit further, in the goagain example program the file handle for the accept listener is always 7, however its really 3 since its the third file you pass into StartProcess. If I hardcode it to 3 it works both on linux and OSX, not sure why the 7 also works on linux.

LSOF:
COMMAND    PID      USER   FD     TYPE             DEVICE  SIZE/OFF    NODE NAME
test_go_a 8684 kanwisher  cwd      DIR                1,1      1462 4370075 /Users/kanwisher/projects/rt/nitro
test_go_a 8684 kanwisher  txt      REG                1,1   2044864 7723337 /Users/kanwisher/projects/rt/nitro/test_go_again
test_go_a 8684 kanwisher  txt      REG                1,1    600576    9397 /usr/lib/dyld
test_go_a 8684 kanwisher  txt      REG                1,1 302747648  424298 /private/var/db/dyld/dyld_shared_cache_x86_64
test_go_a 8684 kanwisher    0u     CHR               16,0  0t606705    7333 /dev/ttys000
test_go_a 8684 kanwisher    1u     CHR               16,0  0t606705    7333 /dev/ttys000
test_go_a 8684 kanwisher    2u     CHR               16,0  0t606705    7333 /dev/ttys000
test_go_a 8684 kanwisher    3u    IPv4 0xca4bc68557828b7f       0t0     TCP localhost:48879 (LISTEN)
test_go_a 8684 kanwisher    4     PIPE 0xffffff8026a3e370     16384         ->0xffffff8026a405d0
test_go_a 8684 kanwisher    5     PIPE 0xffffff8026a405d0     16384         ->0xffffff8026a3e370
test_go_a 8684 kanwisher    6u  KQUEUE                                      count=0, state=0x2
test_go_a 8684 kanwisher    8     PIPE 0xffffff8026a40890     16384         ->0xffffff8026a40100

P.S I got the number 7 from doing 
    log.Printf("GOAGAIN_FD %v", f)

**Comment by rcrowley** [comment] 2013-03-26 03:52
In an unrelated turn of events, I read `pkg/net` in great detail the other day and now believe this is a duplicate of #5.  I won't close this issue until that can be confirmed, however.

**Comment by rcrowley** [comment] 2013-03-26 06:02
@mattkanwisher can you verify that this is fixed?

**Closed as completed by rcrowley** 2013-03-26 06:02 UTC
